server:
  port: 8086
spring:
  application:
    name: "CartaoCreditoTransacao"
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5442/transacoes}
    username: ${DATABASE_USERNAME:keycloak}
    password: ${DATABASE_URL:password}
    jpa:
      showSql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
        ddlAuto: create-drop